import Loading from "../loading";

export const metadata = {
	title: "Katalog Product | Business Partner",
	description: "Generated by create next app",
};

export default function KatalogProducts({ children }) {
	return (
		<main>
			{children}
		</main>
	);
}
