import "./globals.css";

// PROVIDER
import UserProvider from "../context/user/user-context";
import FeedProvider from "../context/feed/feed-context";
import ProductProvider from "../context/product/product-context";
import SidebarProvider from "../context/sidebar/sidebar-context";
import OrderDetailProvider from "../context/order-detail/order-detail";
import DeliveryDetailProvider from "../context/delivery-detail/delivery-detail";
import DeliveryListProvider from "../context/delivery-list/delivery-list";

export const metadata = {
	title: "Andaru Business Partner",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<head>
				<link rel='preconnect' href='https://fonts.googleapis.com' />
				<link
					rel='preconnect'
					href='https://fonts.gstatic.com'
					crossOrigin='true'
				/>
				<link
					href='https://fonts.googleapis.com/css2?family=Outfit:wght@100;200;300;400;500;600;700;800;900&display=swap'
					rel='stylesheet'
				/>
			</head>
			<UserProvider>
				<FeedProvider>
					<ProductProvider>
						<SidebarProvider>
							<OrderDetailProvider>
								<DeliveryDetailProvider>
									<DeliveryListProvider>
										<body>{children}</body>
									</DeliveryListProvider>
								</DeliveryDetailProvider>
							</OrderDetailProvider>
						</SidebarProvider>
					</ProductProvider>
				</FeedProvider>
			</UserProvider>
		</html>
	);
}
